// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_kids_casual_tapper = "CgkIvLXV9rMQEAIQFA"; // <GPGSID>
        public const string achievement_bug_hunter = "CgkIvLXV9rMQEAIQDA"; // <GPGSID>
        public const string achievement_casual_tapper = "CgkIvLXV9rMQEAIQDg"; // <GPGSID>
        public const string achievement_bug_terminator = "CgkIvLXV9rMQEAIQDQ"; // <GPGSID>
        public const string achievement_kids_bug_hater = "CgkIvLXV9rMQEAIQEQ"; // <GPGSID>
        public const string leaderboard_classic = "CgkIvLXV9rMQEAIQCA"; // <GPGSID>
        public const string achievement_kids_ultimate_tapper = "CgkIvLXV9rMQEAIQFg"; // <GPGSID>
        public const string achievement_pro_tapper = "CgkIvLXV9rMQEAIQDw"; // <GPGSID>
        public const string achievement_bug_hater = "CgkIvLXV9rMQEAIQCw"; // <GPGSID>
        public const string achievement_kids_bug_terminator = "CgkIvLXV9rMQEAIQEw"; // <GPGSID>
        public const string achievement_kids_pro_tapper = "CgkIvLXV9rMQEAIQFQ"; // <GPGSID>
        public const string achievement_kids_bug_hunter = "CgkIvLXV9rMQEAIQEg"; // <GPGSID>
        public const string leaderboard_kids = "CgkIvLXV9rMQEAIQCQ"; // <GPGSID>
        public const string achievement_ultimate_tapper = "CgkIvLXV9rMQEAIQEA"; // <GPGSID>

}

