using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class GameAnalyticsConfig{
	// EVENTS
	public const string COMMON = "COMMON";
	public const string CLICK = "CLICK";
	public const string IN_GAME = "IN_GAME";
	public const string FEATURES = "FEATURE";
	public const string ADS = "ADS";

	// COMMON
	public const string OPEN_GAME = "OPEN_GAME";
	public const string QUIT_GAME = "QUIT_GAME";
	// common


	// CLICK
	public const string CLICK_PLAY_MAIN_MENU_BUTTON = "CLICK_PLAY_MAIN_MENU_BUTTON";
	public const string CLICK_HIGH_SCORE_MAIN_MENU_BUTTON = "CLICK_HIGH_SCORE_MAIN_MENU_BUTTON";
	public const string CLICK_OPTION_MAIN_MENU_BUTTON = "CLICK_OPTION_MAIN_MENU_BUTTON";

	public const string CLICK_CLASSIC_GAME_MODE_BUTTON = "CLICK_CLASSIC_GAME_MODE_BUTTON";
	public const string CLICK_KIDS_GAME_MODE_BUTTON = "CLICK_KIDS_GAME_MODE_BUTTON";
	public const string CLICK_MAIN_MENU_GAME_MODE_BUTTON = "CLICK_MAIN_MENU_GAME_MODE_BUTTON";

	public const string CLICK_IN_GAME_PAUSED_BUTTON = "CLICK_IN_GAME_PAUSED_BUTTON";
	public const string CLICK_IN_GAME_PAUSED_RESUME_BUTTON = "CLICK_IN_GAME_PAUSED_RESUME_BUTTON";
	public const string CLICK_IN_GAME_PAUSED_RESTART_BUTTON = "CLICK_IN_GAME_PAUSED_RESTART_BUTTON";
	public const string CLICK_IN_GAME_PAUSED_QUIT_BUTTON = "CLICK_IN_GAME_PAUSED_QUIT_BUTTON";

	public const string CLICK_TRY_AGAIN_GAME_OVER_BUTTON = "CLICK_TRY_AGAIN_GAME_OVER_BUTTON";
	public const string CLICK_MAIN_MENU_GAME_OVER_BUTTON = "CLICK_MAIN_MENU_GAME_OVER_BUTTON";
	public const string CLICK_HIGH_SCORE_GAME_OVER_BUTTON = "CLICK_HIGH_SCORE_GAME_OVER_BUTTON";
	public const string CLICK_SHARE_GAME_OVER_BUTTON = "CLICK_SHARE_GAME_OVER_BUTTON";

	public const string CLICK_PLAY_OPTION_BUTTON = "CLICK_PLAY_OPTION_BUTTON";
	public const string CLICK_ACHIEVEMENT_OPTION_BUTTON = "CLICK_ACHIEVEMENT_OPTION_BUTTON";
	public const string CLICK_MAIN_MENU_GAME_OPTION_BUTTON = "CLICK_MAIN_MENU_GAME_OPTION_BUTTON";

	public const string CLICK_VIBRATION_OPTION = "CLICK_VIBRATION_OPTION";
	public const string VIBRATION_VALUE_OPTION = "VIBRATION_VALUE_OPTION";

	public const string MUSIC_OPTION_VALUE = "MUSIC_OPTION_VALUE";
	public const string SFX_OPTION_VALUE = "SFX_OPTION_VALUE";

	// quit
	public const string CLICK_QUIT_BUTTON = "CLICK_QUIT_BUTTON";
	public const string CLICK_YES_QUIT_BUTTON = "CLICK_YES_QUIT_BUTTON";
	public const string CLICK_NO_QUIT_BUTTON = "CLICK_NO_QUIT_BUTTON";
	public const string OPEN_QUIT_POPUP = "OPEN_QUIT_POPUP";

	// rate us
	public const string CLICK_RATE_IT_RATE_US_BUTTON = "CLICK_RATE_IT_RATE_US_BUTTON";
	public const string CLICK_REMIND_ME_LATER_RATE_US_BUTTON = "CLICK_REMIND_ME_LATER_RATE_US_BUTTON";
	public const string CLICK_NO_THANKS_RATE_US_BUTTON = "CLICK_NO_THANKS_RATE_US_BUTTON";


	// FEATURES
	public const string GOOGLE_PLAY_LOGIN = "GOOGLE_PLAY_LOGIN";

	public const string OPEN_GOOGLE_PLAY_HIGH_SCORE = "OPEN_GOOGLE_PLAY_HIGH_SCORE";
	public const string OPEN_GOOGLE_PLAY_ACHIEVEMENT = "OPEN_GOOGLE_PLAY_ACHIEVEMENT";

	public const string POST_GOOGLE_PLAY_HIGH_SCORE = "POST_GOOGLE_PLAY_HIGH_SCORE";
	public const string POST_GOOGLE_PLAY_ACHIEVEMENT = "POST_GOOGLE_PLAY_ACHIEVEMENT";

	public const string GAME_CENTER_LOGIN = "GAME_CENTER_LOGIN";

	public const string OPEN_GAME_CENTER_HIGH_SCORE = "OPEN_GAME_CENTER_HIGH_SCORE";
	public const string OPEN_GAME_CENTER_ACHIEVEMENT = "OPEN_GAME_CENTER_ACHIEVEMENT";

	public const string POST_GAME_CENTER_HIGH_SCORE = "POST_GAME_CENTER_HIGH_SCORE";
	public const string POST_GAME_CENTER_ACHIEVEMENT = "POST_GAME_CENTER_ACHIEVEMENT";

	// ADS
	public const string LOAD_BANNER_ADS = "LOAD_BANNER_ADS";
	public const string LOAD_FAILED_BANNER_ADS = "LOAD_FAILED_BANNER_ADSBANNER_ADS";
	public const string OPEN_BANNER_ADS = "OPEN_BANNER_ADS";
	public const string CLOSE_BANNER_ADS = "CLOSE_BANNER_ADS";
	public const string LEAVING_APPLICAION_BANNER_ADS = "LEAVING_APPLICAION_BANNER_ADS";

	public const string LOAD_INTER_STITIAL_ADS = "LOAD_INTER_STITIAL_ADS";
	public const string LOAD_FAILED_INTER_STITIAL_ADS = "LOAD_FAILED_INTER_STITIAL_ADSINTER_STITIAL_ADS";
	public const string OPEN_INTER_STITIAL_ADS = "OPEN_INTER_STITIAL_ADS";
	public const string CLOSE_INTER_STITIAL_ADS = "CLOSE_INTER_STITIAL_ADS";
	public const string LEAVING_APPLICAION_INTER_STITIAL_ADS = "LEAVING_APPLICAION_INTER_STITIAL_ADS";
	// ADS

	// IN GAME
	public const string TOTAL_GAME_COUNT_PER_SESSION = "TOTAL_GAME_COUNT_PER_SESSION";

	public const string CLASSIC_MIN_COMBO = "CLASSIC_MIN_COMBO";
	public const string CLASSIC_BEST_COMBO = "CLASSIC_BEST_COMBO";

	public const string CLASSIC_MIN_HIGH_SCORE = "CLASSIC_MIN_HIGH_SCORE";
	public const string CLASSIC_BEST_HIGH_SCORE = "CLASSIC_BEST_HIGH_SCORE";

	public const string CLASSIC_TOTAL_BUGS_KILLS_PER_GAME = "CLASSIC_TOTAL_BUGS_KILLS_PER_GAME";
	public const string CLASSIC_OVER_ALL_BUG_TOTAL_KILLS = "CLASSIC_OVER_ALL_BUG_TOTAL_KILLS";


	public const string CLASSIC_DURATION_PER_ROUND = "CLASSIC_DURATION_PER_ROUND";

	public const string CLASSIC_ANT_QUEEN_KILL = "CLASSIC_ANT_QUEEN_KILL";
	public const string CLASSIC_ANT_WORKER_KILL = "CLASSIC_ANT_WORKER_KILL";
	public const string CLASSIC_ANT_WARRIOR_KILL = "CLASSIC_ANT_WARRIOR_KILL";
	public const string CLASSIC_SPIDER_KILL = "CLASSIC_SPIDER_KILL";
	public const string CLASSIC_SMALL_SPIDER_KILL = "CLASSIC_SMALL_SPIDER_KILL";
	public const string CLASSIC_COCKROACH_KILL = "CLASSIC_COCKROACH_KILL";


	public const string KIDS_MIN_COMBO = "KIDS_MIN_COMBO";
	public const string KIDS_BEST_COMBO = "KIDS_BEST_COMBO";

	public const string KIDS_MIN_HIGH_SCORE = "KIDS_MIN_HIGH_SCORE";
	public const string KIDS_BEST_HIGH_SCORE = "KIDS_BEST_HIGH_SCORE";

	public const string KIDS_TOTAL_BUGS_KILLS_PER_GAME = "CLASSIC_TOTAL_BUGS_KILLS_PER_GAME";
	public const string KIDS_OVER_ALL_BUG_TOTAL_KILLS = "CLASSIC_OVER_ALL_BUG_TOTAL_KILLS";

	public const string KIDS_DURATION_PER_ROUND = "KIDS_DURATION_PER_ROUND";

	public const string KIDS_ANT_QUEEN_KILL = "KIDS_ANT_QUEEN_KILL";
	public const string KIDS_ANT_WORKER_KILL = "KIDS_ANT_WORKER_KILL";
	public const string KIDS_ANT_WARRIOR_KILL = "KIDS_ANT_WARRIOR_KILL";
	public const string KIDS_SPIDER_KILL = "KIDS_SPIDER_KILL";
	public const string KIDS_SMAL_SPIDER_KILL = "KIDS_SMAL_SPIDER_KILL";
	public const string KIDS_COCKROACH_KILL = "KIDS_COCKROACH_KILL";
	// IN GAME
}
